version: '3'

services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=book_social_network
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-demo  # Added to ensure both services are on the same network

volumes:
  postgres:
    driver: local

networks:
  spring-demo:
    driver: bridge